# Generated by Django 3.2.6 on 2021-08-03 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_first',
        ),
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next', to='Agah.question', verbose_name='سوال بعدی'),
        ),
        migrations.AlterField(
            model_name='region',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='Agah.question', verbose_name='پرسش'),
        ),
        migrations.AlterField(
            model_name='region',
            name='value',
            field=models.PositiveSmallIntegerField(verbose_name='کد'),
        ),
    ]
