# Generated by Django 3.2.6 on 2021-08-03 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0002_auto_20210803_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='Agah.question', verbose_name='پرسش'),
        ),
    ]
