# Generated by Django 3.2.6 on 2021-08-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0003_alter_region_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[(1, 'متن')], default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.PositiveSmallIntegerField(verbose_name='کد'),
        ),
    ]
