# Generated by Django 3.2.6 on 2021-08-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0004_auto_20210803_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('IntegerField', 'عدد'), ('CharField', 'متن'), ('ChoiceField', 'کرکره ی'), ('RadioSelect', 'تک انتخاب'), ('MultipleChoiceField', 'چند انتخاب')], max_length=50),
        ),
    ]
