# Generated by Django 3.2.6 on 2021-08-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0005_alter_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responder',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='responder',
            old_name='family',
            new_name='lastname',
        ),
    ]
