# Generated by Django 3.2.6 on 2021-08-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0006_auto_20210803_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='option',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='point',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(default=None, max_length=10, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Agah.question', verbose_name='پرسش'),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='responser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Agah.responder', verbose_name='پاسخگو'),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Agah.survey', verbose_name='پرسشنامه'),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='total_point',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='مجموع امتیاز'),
        ),
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(verbose_name='محسابه سن اتومات'),
        ),
    ]
