# Generated by Django 3.2.6 on 2021-08-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0008_answer_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='point',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='امتیاز'),
        ),
    ]
