# Generated by Django 3.2.6 on 2021-08-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0009_alter_answer_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Agah.option', verbose_name='گزینه ی انتخاب شده'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(default=None, max_length=10, verbose_name='مقدار'),
        ),
    ]
