# Generated by Django 3.2.6 on 2021-08-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0010_auto_20210814_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='مقدار'),
        ),
    ]
