# Generated by Django 3.2.6 on 2021-08-15 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agah', '0011_alter_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Agah.option', verbose_name='جنسیت'),
        ),
    ]
